from typing import List, Dict, Any, Tuple
import datetime


class AIFraudService:
    def __init__(self):
        # In a real environment, this would initialize LangChain plugins
        # for perplexity/watermark analysis on candidate responses.
        self.baseline_trust_score = 100

    def analyze_telemetry(
        self, telemetry_events: List[Dict[str, Any]]
    ) -> Tuple[int, List[Dict[str, Any]]]:
        """
        Analyzes raw browser telemetry points during an assessment.
        Calculates deductions and returns the final Trust Score and an Audit Log.
        """
        deductions = 0
        audit_log = []
        tab_switches = 0
        copy_pastes = 0

        for event in telemetry_events:
            event_type = event.get("type")
            timestamp = event.get("timestamp", datetime.datetime.now().isoformat())
            details = event.get("details", {})

            if event_type == "tab_switch":
                duration = details.get("durationSeconds", 0)
                if duration > 5:
                    tab_switches += 1
                    deductions += 5
                    audit_log.append(
                        {
                            "timestamp": timestamp,
                            "severity": "low",
                            "message": f"Candidate lost window focus for {duration} seconds.",
                            "penalty": -5,
                        }
                    )

            elif event_type == "paste":
                char_count = details.get("characterCount", 0)
                if char_count > 100:
                    copy_pastes += 1
                    deductions += 25
                    audit_log.append(
                        {
                            "timestamp": timestamp,
                            "severity": "medium",
                            "message": f"Candidate pasted {char_count} characters of code instantly.",
                            "penalty": -25,
                        }
                    )

            elif event_type == "llm_watermark_match":
                probability = details.get("probability", 0)
                if probability > 0.85:
                    deductions += 50
                    audit_log.append(
                        {
                            "timestamp": timestamp,
                            "severity": "high",
                            "message": f"LLM vector analysis estimates {probability * 100}% probability the text was generated by AI.",
                            "penalty": -50,
                        }
                    )

            elif event_type == "multi_voice_detected":
                deductions += 100
                audit_log.append(
                    {
                        "timestamp": timestamp,
                        "severity": "critical",
                        "message": "Multiple distinct voices detected by speaker diarization during assessment.",
                        "penalty": -100,
                    }
                )

        # Apply specific escalating penalties
        if tab_switches >= 5:
            deductions += 20
            audit_log.append(
                {
                    "timestamp": datetime.datetime.now().isoformat(),
                    "severity": "medium",
                    "message": f"Frequent pattern detected: Switched tabs {tab_switches} times over the session.",
                    "penalty": -20,
                }
            )

        final_trust_score = max(0, self.baseline_trust_score - deductions)
        return final_trust_score, audit_log

    def determine_shield_status(self, score: int) -> str:
        """Determines the color of the recruiter trust shield."""
        if score >= 90:
            return "Green"
        elif score >= 65:
            return "Yellow"
        else:
            return "Red"

    def determine_trust_status(self, score: int) -> str:
        if score >= 90:
            return "Verified Authentic"
        elif score >= 65:
            return "Verified with Warnings"
        else:
            return "Disqualified (Fraud Alerts)"
