"""add sidebar_preferences to user

Revision ID: 4bf33476bd6e
Revises: db64c0679874
Create Date: 2026-06-19 12:15:08.679302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bf33476bd6e'
down_revision = 'db64c0679874'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navigation_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('required_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('navigation_subgroups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('required_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['navigation_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('navigation_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=True),
    sa.Column('subgroup_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('href', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('exact', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('required_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['navigation_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subgroup_id'], ['navigation_subgroups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    pass
    op.add_column('users', sa.Column('sidebar_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sidebar_preferences')
    op.create_table('site_content',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('section_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('site_content_pkey'))
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('excerpt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), server_default=sa.text("'General'::character varying"), autoincrement=False, nullable=True),
    sa.Column('featured_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('read_time', sa.VARCHAR(), server_default=sa.text("'5 min'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('blog_posts_pkey')),
    sa.UniqueConstraint('slug', name=op.f('blog_posts_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('navigation_links')
    op.drop_table('navigation_subgroups')
    op.drop_table('navigation_modules')
    # ### end Alembic commands ###
