"""Init missing tables

Revision ID: 838ab9c1a4ba
Revises: 0654ad1544c4
Create Date: 2026-06-18 16:41:08.356463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838ab9c1a4ba'
down_revision = '0654ad1544c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
