import os
import logging
from fastapi import APIRouter, Depends
from core.response import success_response
from core.dependencies import get_db, get_validated_wallet
import google.generativeai as genai

logger = logging.getLogger(__name__)

router = APIRouter()

@router.post("/build")
async def extract_and_build_portfolio(
    wallet: str = Depends(get_validated_wallet)
):
    """
    AI Portfolio Builder Endpoint.
    Generates a structured marketing portfolio based on verified profile and proof-score.
    """
    db = await get_db()

    # 1. Fetch Candidate Data
    user_resp = db.table("users").select("*").eq("wallet_address", wallet).single().execute()
    if not user_resp.data:
        return success_response(data={"error": "User profile not found"}, status_code=404)

    user_data = user_resp.data
    full_name = user_data.get("full_name", "Verified Talent")
    proof_score = user_data.get("reputation_score", 500)
    skills = user_data.get("profile_data", {}).get("skills", ["Software Engineering"])
    github_handle = user_data.get("dynamic_fields", {}).get("github_handle", "dev")

    # 2. AI Generation
    api_key = os.getenv("GOOGLE_API_KEY")
    portfolio_content = ""

    if api_key:
        try:
            genai.configure(api_key=api_key)
            model = genai.GenerativeModel("gemini-1.5-flash")
            
            prompt = f"""Generate a professional engineering portfolio summary for {full_name}.
            Proof-Score: {proof_score}/1000
            Skills: {', '.join(skills)}
            GitHub: github.com/{github_handle}
            
            Format as clean Markdown. Include sections: Executive Summary, Verified Achievements, and Tech Stack.
            Highlight the fact that their skills are AI-verified.
            """
            
            response = model.generate_content(prompt)
            portfolio_content = response.text
        except Exception as e:
            logger.error(f"AI Portfolio Generation failed: {e}")

    if not portfolio_content:
        # Fallback Template
        portfolio_content = f"""
# {full_name} | Verified Talent
**Proof-Score:** {proof_score}/1000 ✨

## Executive Summary
{full_name} is an AI-verified professional with proven expertise in {', '.join(skills[:3])}.

## Key Verified Achievements
- **High Integrity:** Verified Proof-Score of {proof_score} based on real-world simulations.
- **Skill Mastery:** Proven technical competence in {len(skills)} verified domains.

---
*Auto-generated by Best Hiring Tool AI*
        """

    return success_response(data={
        "wallet_address": wallet,
        "portfolio": {
            "type": "markdown",
            "content": portfolio_content.strip(),
            "last_updated": "2026-05-01T00:00:00Z"
        }
    })
