-- Migration 31: AI Interview Preparation System
-- Creates a table to store dynamically generated interview questions.

CREATE TABLE IF NOT EXISTS ai_interview_questions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    job_id UUID REFERENCES jobs(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    options JSONB NOT NULL, -- Format: ["Option A", "Option B", "Option C", "Option D"]
    correct_answer TEXT NOT NULL,
    difficulty TEXT DEFAULT 'Intermediate',
    source TEXT DEFAULT 'AI', -- 'AI' or 'HR'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster retrieval
CREATE INDEX IF NOT EXISTS idx_interview_user_job ON ai_interview_questions(user_id, job_id);

COMMENT ON TABLE ai_interview_questions IS 'Stores MCQ interview questions generated by AI or set by HR for candidates.';
