-- 59_sync_missing_columns.sql
CREATE EXTENSION IF NOT EXISTS vector;
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS about TEXT,
ADD COLUMN IF NOT EXISTS resume_url VARCHAR,
ADD COLUMN IF NOT EXISTS banner_url VARCHAR,
ADD COLUMN IF NOT EXISTS visibility_mode VARCHAR DEFAULT 'PUBLIC',
ADD COLUMN IF NOT EXISTS open_to_work BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS github_url VARCHAR,
ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR,
ADD COLUMN IF NOT EXISTS portfolio_url VARCHAR,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
ADD COLUMN IF NOT EXISTS embedding vector(768);

ALTER TABLE experiences
ADD COLUMN IF NOT EXISTS profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS title VARCHAR,
ADD COLUMN IF NOT EXISTS is_current BOOLEAN DEFAULT FALSE;

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS url VARCHAR,
ADD COLUMN IF NOT EXISTS skills_used JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS is_portfolio_item BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS embedded_media JSONB DEFAULT '[]'::jsonb;

-- Python model expects 'educations' not 'education'
ALTER TABLE IF EXISTS education RENAME TO educations;

ALTER TABLE IF EXISTS educations 
ADD COLUMN IF NOT EXISTS profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS school VARCHAR;
