import uuid
from datetime import datetime
from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey, Float
from sqlalchemy.dialects.postgresql import UUID
from core.database import Base

class PartnerAccount(Base):
    """
    Universities, Recruitment Agencies, Bootcamps, and Assessment Providers.
    """
    __tablename__ = "partner_accounts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    owner_id = Column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='CASCADE'), nullable=False)
    
    name = Column(String, nullable=False)
    partner_type = Column(String, nullable=False) # UNIVERSITY, AGENCY, BOOTCAMP, ASSESSMENT
    
    website = Column(String, nullable=True)
    is_verified = Column(Boolean, default=False)
    
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)

class Certification(Base):
    """
    Certifications / Micro-credentials created by a Learning Partner.
    e.g. "AWS Certified Developer", "SkillSutra React Expert"
    """
    __tablename__ = "partner_certifications"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    partner_id = Column(UUID(as_uuid=True), ForeignKey('partner_accounts.id', ondelete='CASCADE'), nullable=False)
    
    title = Column(String, nullable=False)
    description = Column(String, nullable=True)
    
    price = Column(Float, default=0.0)
    validity_months = Column(Float, nullable=True) # E.g. 24 months before expiration
    
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)

class AffiliateCommission(Base):
    """
    Tracks revenue generated by users referring companies or courses.
    """
    __tablename__ = "affiliate_commissions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    affiliate_user_id = Column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='CASCADE'), nullable=False)
    
    # What did they refer?
    referred_type = Column(String, nullable=False) # COMPANY_REGISTRATION, COURSE_PURCHASE
    referred_entity_id = Column(String, nullable=False) 
    
    # Financials
    transaction_amount = Column(Float, nullable=False)
    commission_earned = Column(Float, nullable=False) # e.g. 10% of transaction
    
    status = Column(String, default="PENDING") # PENDING, CLEARED, PAID_OUT
    
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
