import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Learn how SkillSutra collects, uses, and protects your personal data.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="container mx-auto px-4 py-24 max-w-4xl">
      <div className="prose prose-slate dark:prose-invert max-w-none">
        <h1 className="text-4xl md:text-5xl font-bold font-heading mb-8 bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">Privacy Policy</h1>
        
        <p className="text-lg text-muted-foreground mb-12">
          Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </p>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">1. Information We Collect</h2>
          <p>
            At SkillSutra, we collect information to provide better services to all our users. We collect information in the following ways:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li><strong>Information you give us:</strong> This includes your name, email address, phone number, and professional details when you register for an account.</li>
            <li><strong>Information we get from your use of our services:</strong> We collect information about the services that you use and how you use them, such as when you visit a web page, view content, or interact with our AI-powered features.</li>
            <li><strong>Professional credentials and verification data:</strong> Information related to your skills, employment history, and Proof Scores generated by our platform.</li>
          </ul>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">2. How We Use Information</h2>
          <p>We use the information we collect from all of our services to provide, maintain, protect and improve them, to develop new ones, and to protect SkillSutra and our users. We also use this information to offer you tailored content – like giving you more relevant job recommendations and search results.</p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">3. AI and Data Processing</h2>
          <p>
            SkillSutra leverages Artificial Intelligence (AI) to enhance talent matching and verify skills. When you submit resumes, portfolios, or complete assessments, our AI models process this data to generate insights, matching scores, and verified credentials. We do not use your personal, identifiable data to train public AI models without your explicit consent.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">4. Information Sharing</h2>
          <p>We do not share personal information with companies, organizations and individuals outside of SkillSutra unless one of the following circumstances applies:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li><strong>With your consent:</strong> We will share personal information with companies (such as employers you apply to) when we have your consent to do so.</li>
            <li><strong>For external processing:</strong> We provide personal information to our affiliates or other trusted businesses or persons to process it for us, based on our instructions and in compliance with our Privacy Policy.</li>
            <li><strong>For legal reasons:</strong> We will share personal information if we have a good-faith belief that access, use, preservation or disclosure of the information is reasonably necessary to meet any applicable law, regulation, legal process or enforceable governmental request.</li>
          </ul>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">5. Data Security</h2>
          <p>We work hard to protect SkillSutra and our users from unauthorized access to or unauthorized alteration, disclosure or destruction of information we hold. We use encryption to keep your data private while in transit and review our information collection, storage and processing practices.</p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">6. Your Rights</h2>
          <p>Depending on your location, you may have certain rights regarding your personal data, including the right to access, correct, delete, or restrict the processing of your personal information. You can exercise these rights by contacting our privacy team.</p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">7. Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, please contact us at <a href="mailto:privacy@skillsutra.com" className="text-primary hover:underline">privacy@skillsutra.com</a>.</p>
        </section>
      </div>
    </div>
  );
}
